全データを取得するdispatchで第二引数にuserデータを入れたが、store/index.jsのfetchItemsアクションで、userデータをどのように扱えば良いのか分からない
heureux-kun/parts-scraps pull request #4
Opened 2020-06-28 14:12 UTC by heureux-kun

2020-06-29 14:28 UTC, watsuyo requested changes

2020-06-29 14:28 UTC, watsuyo commented on store/items.js
> +    const itemArray = []
ここでconsole.log(user)としてuserのデータが出るか確認して下さい！
uidがほしければ、userオブジェクトからuser.uidでuidが取れるはずです！

ただitem全取得にはuser情報は必要なんですか🤔？
uidごとに取得したいのであれば、fetchItemsByUidみたいなactionを作ってuidを元にfirestoreから取得する必要がありそうです

2020-06-29 14:28 UTC, watsuyo commented on store/items.js
> +  },
これは
```js
itemsByCategory: (state, categoryId) => {
    return state.items.filter(item => item.categoryId === categoryId)
  },
```
というgetterにしてvueから呼ぶときに引数にわたしてあげましょう！

2020-06-29 14:28 UTC, watsuyo commented on store/items.js
> +  itemsCategory1: [],
getterを変えるタイミングでここも変えましょう！

2020-06-29 14:28 UTC, watsuyo commented on pages/index.vue
> +        <img v-bind:src="item.downloadUrl">
v-bindは他の箇所にもでてきますが、省略しましょう！
https://jp.vuejs.org/v2/guide/syntax.html#v-bind-%E7%9C%81%E7%95%A5%E8%A8%98%E6%B3%95

2020-06-29 14:28 UTC, watsuyo commented on components/shared/navigation.vue
> +      categories: this.$store.state.categories
getterを使って、かつ値を受け取るのはcomoutedにしましょう！

2020-06-29 14:28 UTC, watsuyo commented on components/shared/header.vue
>              {{ $store.state.user.displayName }}
このあたりもtemplateでstateを参照せずに、computedで受け取りたいですね！

2020-06-30 14:58 UTC, heureux-kun reviewed
修正しました。不明点をコメントしましたので、お手すきの際にご確認をお願いできればと思います。

2020-06-30 14:58 UTC, heureux-kun commented on components/shared/header.vue
>    },
@watsuyo userデータをcomputedでgetterで取得して、createdもしくはmoutedでそのuserを引数に使った'items/fetchItemsByUid'をdispatchすると、どうもuserデータの取得が間に合ってなさそうなのですが、（items.jsの「fetchItemsByUid」actionでconsole.log(user)したところ、取得できていませんでした。）
createdもしくはmounted以外の場所でdispatchする必要がありますでしょうか？

2020-06-30 14:58 UTC, heureux-kun commented on pages/parts/_id.vue
> +      return this.$store.getters['items/itemsCategory(this.$route.params.id)']
@watsuyo items.jsのgetterで
`itemsCategory: (state, categoryId) => {
    return state.items.filter(item => item.categoryId === categoryId)
  },`
を入れたのですが、 このvueファイルで呼び出す方方法が分からずでして、
`this.$route.params.id`
の前に引数を入れないといけないと思うのですが、何を入れるべきでしょうか？

2020-06-30 15:08 UTC, watsuyo commented on components/shared/header.vue
> +    this.$store.dispatch('items/fetchItemsByUid', user)
userはthis.userでないと参照できませんよ！

2020-06-30 15:08 UTC, watsuyo commented on components/shared/header.vue
>    },
@heureux-kun 
コメントしたthisを試して取得できなければ、全てのItemsを取得して、別のcomputedでitemsByUidを作りましょう！

```js
computed: {
  ItemsByUid() {
     return this.Items.filter(item => item.uiserId === this.userUid)
  }
}
```
のようなイメージでfilterしてあげると良いと思います！

2020-06-30 15:52 UTC, heureux-kun commented on components/shared/header.vue
> +    this.$store.dispatch('items/fetchItemsByUid', user)
getterで取得した値も「this」をつけないといけないんですね。ありがとうございます！

2020-06-30 15:54 UTC, heureux-kun commented
（なぜかこのコメントの下にコメント入力欄が出ていなかったので、この場所でコメントさせていただきます）
```
@heureux-kun
コメントしたthisを試して取得できなければ、全てのItemsを取得して、別のcomputedでitemsByUidを作りましょう！

computed: {
  ItemsByUid() {
     return this.Items.filter(item => item.uiserId === this.userUid)
  }
}
のようなイメージでfilterしてあげると良いと思います！
```
this入れても取得できていなかったので、上記の方法でしようと思います。
ありがとうございます！

2020-06-30 15:56 UTC, heureux-kun commented on pages/parts/_id.vue
> +      return this.$store.getters['items/itemsCategory(this.$route.params.id)']
すみません、お手すきの際に上記のコメントの解決方法もご教示いただければと思います。

2020-07-01 14:47 UTC, watsuyo commented on pages/parts/_id.vue
> +      return this.$store.getters['items/itemsCategory(this.$route.params.id)']
@heureux-kun 
見落としていました
```js
this.$store.getters['items/itemsCategory'](this.$route.params.id)
```
こんな感じです！

2020-07-01 17:37 UTC, heureux-kun commented on pages/parts/_id.vue
> +      return this.$store.getters['items/itemsCategory(this.$route.params.id)']
ありがとうございます。上記を実装したところ、
http://localhost:3000/user/parts/1
http://localhost:3000/parts/1
共に、ページに「エラーが発生しました」と出て
consoleに「this.$store.getters.items/itemsByCategory is not a function」といエラーが出ているのですが、何か書き方が悪いでしょうか...？

2020-07-02 01:18 UTC, watsuyo commented on pages/parts/_id.vue
> +      return this.$store.getters['items/itemsCategory(this.$route.params.id)']
@heureux-kun 
あれっエラーでますか
詳細が分からないので、

×` return this.$store.getters['items/itemsCategory(this.$route.params.id)']`
◎`this.$store.getters['items/itemsCategory'](this.$route.params.id)`

ですよ！

2020-07-02 13:09 UTC, heureux-kun commented on pages/parts/_id.vue
> +      return this.$store.getters['items/itemsByCategory'](this.$route.params.id)
@watsuyo すみません間違えて古いコミットにコメントしていたようでした。
`return this.$store.getters['items/itemsByCategory'](this.$route.params.id)`
にしているのですが、エラーが出ておりまして...
（items.jsのgetter名もitemsByCategoryに変えてます）

2020-07-02 13:12 UTC, watsuyo commented on pages/parts/_id.vue
> +      return this.$store.getters['items/itemsByCategory'](this.$route.params.id)
@heureux-kun 
```js
itemsByCategory: (state, categoryId) => {
  console.log(categoryId)
}
```
これはundefindになりますか？

2020-07-02 13:13 UTC, heureux-kun commented on pages/parts/_id.vue
> +      return this.$store.getters['items/itemsByCategory'](this.$route.params.id)
[object Object]で取得できていませんでした！

2020-07-02 13:14 UTC, watsuyo commented on pages/parts/_id.vue
> +      return this.$store.getters['items/itemsByCategory'](this.$route.params.id)
```js
getItems () {
   console.log(this.$route.params.id)
}
```
これはどうでしょう

2020-07-02 13:16 UTC, heureux-kun commented on pages/parts/_id.vue
> +      return this.$store.getters['items/itemsByCategory'](this.$route.params.id)
http://localhost:3000/parts/1にアクセスした時「1 」と出て取得できていました。

2020-07-02 13:17 UTC, watsuyo commented on pages/parts/_id.vue
> +      return this.$store.getters['items/itemsByCategory'](this.$route.params.id)
return this.$route.params.id && this.$store.getters['items/itemsByCategory'](this.$route.params.id)

これはどうでしょう

2020-07-02 13:21 UTC, heureux-kun commented on pages/parts/_id.vue
> +      return this.$store.getters['items/itemsByCategory'](this.$route.params.id)
`this.$store.getters.items/itemsByCategory is not a function`
のエラーが出ています。
items.jsのgetterの書き方が問題でしょうか？

2020-07-05 15:41 UTC, closed without merging